import 'bloc/let_s_you_in_bloc.dart';import 'models/let_s_you_in_model.dart';import 'package:baburam_s_application5/core/app_export.dart';import 'package:baburam_s_application5/widgets/custom_button.dart';import 'package:flutter/material.dart';import 'package:baburam_s_application5/domain/facebookauth/facebook_auth_helper.dart';import 'package:baburam_s_application5/domain/googleauth/google_auth_helper.dart';class LetSYouInScreen extends StatelessWidget {static Widget builder(BuildContext context) { return BlocProvider<LetSYouInBloc>(create: (context) => LetSYouInBloc(LetSYouInState(letSYouInModelObj: LetSYouInModel()))..add(LetSYouInInitialEvent()), child: LetSYouInScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<LetSYouInBloc, LetSYouInState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: ColorConstant.gray900, body: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 11, right: 24, bottom: 11), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgArrowleft, height: getSize(28), width: getSize(28), alignment: Alignment.centerLeft, onTap: () {onTapImgArrowleft(context);}), Spacer(), Padding(padding: getPadding(bottom: 10), child: Text("lbl_let_s_you_in".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold48)), CustomButton(height: getVerticalSize(60), text: "msg_continue_with_f".tr, variant: ButtonVariant.OutlineGray800_1, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingT19, fontStyle: ButtonFontStyle.UrbanistSemiBold16WhiteA700, prefixWidget: Container(margin: getMargin(right: 12), child: CustomImageView(svgPath: ImageConstant.imgFacebook)), onTap: () {onTapContinuewithfacebook(context);}), CustomButton(height: getVerticalSize(60), text: "msg_continue_with_g".tr, margin: getMargin(top: 16), variant: ButtonVariant.OutlineGray800_1, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingT19, fontStyle: ButtonFontStyle.UrbanistSemiBold16WhiteA700, prefixWidget: Container(margin: getMargin(right: 11), child: CustomImageView(svgPath: ImageConstant.imgGoogle24x24)), onTap: () {onTapContinuewithgoogle(context);}), CustomButton(height: getVerticalSize(60), text: "msg_continue_with_a".tr, margin: getMargin(top: 16), variant: ButtonVariant.OutlineGray800_1, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingT19, fontStyle: ButtonFontStyle.UrbanistSemiBold16WhiteA700, prefixWidget: Container(margin: getMargin(right: 12), child: CustomImageView(svgPath: ImageConstant.imgFrame))), CustomImageView(svgPath: ImageConstant.imgGroup16, height: getVerticalSize(9), width: getHorizontalSize(360), margin: getMargin(top: 58)), CustomButton(height: getVerticalSize(55), text: "msg_sign_in_with_pa".tr, margin: getMargin(top: 55), variant: ButtonVariant.OutlineGreenA7003f, onTap: () {onTapSigninwithpassword(context);}), Padding(padding: getPadding(top: 100, bottom: 10), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: getPadding(bottom: 1), child: Text("msg_don_t_have_an_a".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRegular14.copyWith(letterSpacing: getHorizontalSize(0.2)))), GestureDetector(onTap: () {onTapTxtSignup(context);}, child: Padding(padding: getPadding(left: 8, top: 1), child: Text("lbl_sign_up".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistSemiBold14.copyWith(letterSpacing: getHorizontalSize(0.2)))))]))]))));}); } 
onTapImgArrowleft(BuildContext context) { NavigatorService.goBack(); } 
onTapContinuewithfacebook(BuildContext context) async  {             await FacebookAuthHelper().facebookSignInProcess().then((facebookUser) {
              //TODO Actions to be performed after signin
              }).catchError((onError) {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(onError.toString())));
            });
             } 
onTapContinuewithgoogle(BuildContext context) async  {         await GoogleAuthHelper().googleSignInProcess().then((googleUser) {
          if(googleUser!=null){
            //TODO Actions to be performed after signin
          } else {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('user data is empty')));
          }
        }).catchError((onError) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(onError.toString())));
        });
         } 
onTapSigninwithpassword(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signInScreen, ); } 
onTapTxtSignup(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUpBlankScreen, ); } 
 }
