import 'bloc/home_screen_container_bloc.dart';import 'models/home_screen_container_model.dart';import 'package:baburam_s_application5/core/app_export.dart';import 'package:baburam_s_application5/presentation/booking_ongoing_tab_container_page/booking_ongoing_tab_container_page.dart';import 'package:baburam_s_application5/presentation/home_screen_page/home_screen_page.dart';import 'package:baburam_s_application5/presentation/profile_settings_page/profile_settings_page.dart';import 'package:baburam_s_application5/presentation/search_page/search_page.dart';import 'package:baburam_s_application5/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class HomeScreenContainerScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { var arg = ModalRoute.of(context)?.settings.arguments as Map<String, dynamic>; return BlocProvider<HomeScreenContainerBloc>(create: (context) => HomeScreenContainerBloc(HomeScreenContainerState(homeScreenContainerModelObj: HomeScreenContainerModel(), id: arg[NavigationArgs.id]))..add(HomeScreenContainerInitialEvent()), child: HomeScreenContainerScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<HomeScreenContainerBloc, HomeScreenContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: ColorConstant.gray900, body: Navigator(key: navigatorKey, initialRoute: AppRoutes.homeScreenPage, onGenerateRoute: (routeSetting) => PageRouteBuilder(pageBuilder: (ctx, ani, ani1) => getCurrentPage(context, routeSetting.name!), transitionDuration: Duration(seconds: 0))), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));})));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homeScreenPage; case BottomBarEnum.Search: return AppRoutes.searchPage; case BottomBarEnum.Booking: return AppRoutes.bookingOngoingTabContainerPage; case BottomBarEnum.Profile: return AppRoutes.profileSettingsPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.homeScreenPage: return HomeScreenPage.builder(context); case AppRoutes.searchPage: return SearchPage.builder(context); case AppRoutes.bookingOngoingTabContainerPage: return BookingOngoingTabContainerPage.builder(context); case AppRoutes.profileSettingsPage: return ProfileSettingsPage.builder(context); default: return DefaultWidget();} } 
 }
